### ISSUE TITLE
react  index.js  export 报错，建议包module.export 导出

### ISSUE THREAD

**Issue by liruiqing7** [LuckDraw/react-luck-draw#1]
// export { LuckyWheel, LuckyGrid } from './dist/react-luck-draw.cjs.js'

module.exports = require('./dist/react-luck-draw.cjs.js');

![image](https://user-images.githubusercontent.com/42953484/113377391-c2fac280-93a6-11eb-8220-9d765551f63a.png)

**Comment by liruiqing7** [comment]
// export { LuckyWheel, LuckyGrid } from './dist/react-luck-draw.cjs.js'

module.exports = require('./dist/react-luck-draw.cjs.js');

![Uploading image.png…]()

**Comment by liruiqing7** [comment]
![Uploading image.png…]()

**Comment by jian263994241** [comment]
用这个吧 react-lucky-canvas

**Comment by buuing** [comment]
> 用这个吧 react-lucky-canvas

你这个可以支持react@15以及更低的版本吗

**Comment by buuing** [comment]
> 用这个吧 react-lucky-canvas

如果可以的话, 非常**欢迎提交PR**, 官网上面会展示**所有的贡献者**😎
