### ISSUE TITLE
转盘抽奖：扇形背景色 是否可以增加背景图片

### ISSUE THREAD

**Issue by LuSSun** [LuckDraw/react-luck-draw#2]
有这么一个场景，大转盘的扇形的背景色用作图片，去铺满整个扇形区域。这种方案在这个项目可以推进么？

**Comment by buuing** [comment]
你是想把扇形当做奖品区域的背景吗?
理论上来说应该是可以的, 直接设置宽度和高度100%可以尝试一下

**Comment by LuSSun** [comment]
> 你是想把扇形当做奖品区域的背景吗?
> 理论上来说应该是可以的, 直接设置宽度和高度100%可以尝试一下

嗯，是的，把奖品区域当做背景，使用prizes. imgs设置图片的宽高100%，会出现图片部分超出扇形，
![image](https://user-images.githubusercontent.com/25789628/113801178-e5b41f00-978a-11eb-97ce-81ad69f6cf2e.png) 类似这种情况。
还打算在prizes.background用图片路径，也没成功

**Comment by buuing** [comment]
你让ui给你按照想要的角度切一个正好的扇形不就得了
`prizes[index].background`只能设置颜色

**Comment by LuSSun** [comment]
好的，谢谢
