### ISSUE TITLE
大转盘的背景颜色可以传渐变色了 如果可以需要怎么传参数

### ISSUE THREAD

**Issue by wangqiang1122** [LuckDraw/react-luck-draw#3]

**Comment by buuing** [comment]
....考虑到ui设计的渐变色太过于复杂且变化多端, 我增加了blocks里面可以传递背景图片的功能
所以, 如果你想使用渐变色的话, 直接让UI切出来一整个合适的圆形即可, 然后设置当前背景跟随旋转

**Comment by wangqiang1122** [comment]
大转盘的奖品的背景颜色 也没有传渐变色吗

**Comment by buuing** [comment]
> 大转盘的奖品的背景颜色 也没有传渐变色吗

奖品你无需设置颜色, 如果你没设置颜色的话, 当前扇形就是透明色, 你就可以直接看到blocks里面设置的背景图片
